/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudyPlanRouteImport } from './routes/_app/study-plan'
import { Route as AppQuestionBankRouteImport } from './routes/_app/question-bank'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppMockExamRouteImport } from './routes/_app/mock-exam'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as ApiPublicStudyNotesRouteImport } from './routes/api/public/study-notes'
import { Route as ApiPublicPdfQuestionsRouteImport } from './routes/api/public/pdf-questions'
import { Route as ApiPublicGenerateQuestionsRouteImport } from './routes/api/public/generate-questions'
import { Route as AppCoursesSlugRouteImport } from './routes/_app/courses.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyPlanRoute = AppStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionBankRoute = AppQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppMockExamRoute = AppMockExamRouteImport.update({
  id: '/mock-exam',
  path: '/mock-exam',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicStudyNotesRoute = ApiPublicStudyNotesRouteImport.update({
  id: '/api/public/study-notes',
  path: '/api/public/study-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfQuestionsRoute = ApiPublicPdfQuestionsRouteImport.update({
  id: '/api/public/pdf-questions',
  path: '/api/public/pdf-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateQuestionsRoute =
  ApiPublicGenerateQuestionsRouteImport.update({
    id: '/api/public/generate-questions',
    path: '/api/public/generate-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCoursesSlugRoute = AppCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/mock-exam': typeof AppMockExamRoute
  '/practice': typeof AppPracticeRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/study-plan': typeof AppStudyPlanRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/pdf-questions': typeof ApiPublicPdfQuestionsRoute
  '/api/public/study-notes': typeof ApiPublicStudyNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/mock-exam': typeof AppMockExamRoute
  '/practice': typeof AppPracticeRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/study-plan': typeof AppStudyPlanRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/pdf-questions': typeof ApiPublicPdfQuestionsRoute
  '/api/public/study-notes': typeof ApiPublicStudyNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mock-exam': typeof AppMockExamRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/question-bank': typeof AppQuestionBankRoute
  '/_app/study-plan': typeof AppStudyPlanRoute
  '/_app/courses/$slug': typeof AppCoursesSlugRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/pdf-questions': typeof ApiPublicPdfQuestionsRoute
  '/api/public/study-notes': typeof ApiPublicStudyNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/courses'
    | '/dashboard'
    | '/mock-exam'
    | '/practice'
    | '/question-bank'
    | '/study-plan'
    | '/courses/$slug'
    | '/api/public/generate-questions'
    | '/api/public/pdf-questions'
    | '/api/public/study-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/courses'
    | '/dashboard'
    | '/mock-exam'
    | '/practice'
    | '/question-bank'
    | '/study-plan'
    | '/courses/$slug'
    | '/api/public/generate-questions'
    | '/api/public/pdf-questions'
    | '/api/public/study-notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/analytics'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/mock-exam'
    | '/_app/practice'
    | '/_app/question-bank'
    | '/_app/study-plan'
    | '/_app/courses/$slug'
    | '/api/public/generate-questions'
    | '/api/public/pdf-questions'
    | '/api/public/study-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicGenerateQuestionsRoute: typeof ApiPublicGenerateQuestionsRoute
  ApiPublicPdfQuestionsRoute: typeof ApiPublicPdfQuestionsRoute
  ApiPublicStudyNotesRoute: typeof ApiPublicStudyNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study-plan': {
      id: '/_app/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof AppStudyPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-bank': {
      id: '/_app/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AppQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock-exam': {
      id: '/_app/mock-exam'
      path: '/mock-exam'
      fullPath: '/mock-exam'
      preLoaderRoute: typeof AppMockExamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/study-notes': {
      id: '/api/public/study-notes'
      path: '/api/public/study-notes'
      fullPath: '/api/public/study-notes'
      preLoaderRoute: typeof ApiPublicStudyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf-questions': {
      id: '/api/public/pdf-questions'
      path: '/api/public/pdf-questions'
      fullPath: '/api/public/pdf-questions'
      preLoaderRoute: typeof ApiPublicPdfQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-questions': {
      id: '/api/public/generate-questions'
      path: '/api/public/generate-questions'
      fullPath: '/api/public/generate-questions'
      preLoaderRoute: typeof ApiPublicGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/courses/$slug': {
      id: '/_app/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesSlugRoute: typeof AppCoursesSlugRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesSlugRoute: AppCoursesSlugRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMockExamRoute: typeof AppMockExamRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppQuestionBankRoute: typeof AppQuestionBankRoute
  AppStudyPlanRoute: typeof AppStudyPlanRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMockExamRoute: AppMockExamRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppQuestionBankRoute: AppQuestionBankRoute,
  AppStudyPlanRoute: AppStudyPlanRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicGenerateQuestionsRoute: ApiPublicGenerateQuestionsRoute,
  ApiPublicPdfQuestionsRoute: ApiPublicPdfQuestionsRoute,
  ApiPublicStudyNotesRoute: ApiPublicStudyNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
